Repository upskill-team/Back-End-DSW, pull requests merged in 2025-08, with the labels that each got.

#11 ref: Move appeal business logic to service layer
  dist/tsconfig.tsbuildinfo
  src/models/appeal/appeal.controller.ts
  src/models/appeal/appeal.entity.ts
  src/models/appeal/appeal.http
  src/models/appeal/appeal.service.ts
Labels: needs-review, refactor

#12 feat: Implement Valibot input validation in Appeal
  dist/tsconfig.tsbuildinfo
  src/models/appeal/appeal.controller.ts
  src/models/appeal/appeal.http
  src/models/appeal/appeal.routes.ts
  src/models/appeal/appeal.schemas.ts
Labels: needs-review, feature

#13 feat: Secure Appeal endpoints with authMiddleware
  dist/tsconfig.tsbuildinfo
  src/models/appeal/appeal.controller.ts
  src/models/appeal/appeal.entity.ts
  src/models/appeal/appeal.http
  src/models/appeal/appeal.routes.ts
  src/models/appeal/appeal.schemas.ts
  src/models/appeal/appeal.service.ts
Labels: needs-review, feature

#18 chore(workflow): Add automated issue templates
  .github/ISSUE_TEMPLATE/nueva-funcionalidad.md
  .github/ISSUE_TEMPLATE/reporte-bug.md
Labels: chore

#19 refactor: add services layers
  .github/workflows/auto-pr.yml
  src/models/courseType/courseType.controller.ts
  src/models/courseType/courseType.services.ts
  src/models/institution/institution.controller.ts
  src/models/institution/institution.services.ts
  src/models/professor/professor.controller.ts
  src/models/professor/professor.services.ts
  src/models/student/student.controller.ts
  src/models/student/student.services.ts
Labels: needs-review, refactor

#21 chore: Change the feature and bug templates
  .github/ISSUE_TEMPLATE/nueva-funcionalidad.md
  .github/ISSUE_TEMPLATE/reporte-bug.md
Labels: needs-review, chore

#32 fix: Corrige el logout instantáneo después de un login exitoso
  dist/tsconfig.tsbuildinfo
  src/auth/auth.service.ts
Labels: needs-review, bugfix

#34 Feat: Corregir y Mejorar Lógica de Gestión de Solicitudes
  dist/tsconfig.tsbuildinfo
  src/models/appeal/appeal.service.ts
Labels: needs-review, feature, bugfix

#41 refactor(course): Estandarizar controlador, servicio y asegurar endpoints
  src/models/course/course.controller.ts
  src/models/course/course.routes.ts
  src/models/course/course.services.ts
Labels: needs-review, refactor

#42 chore: Add PR template and remove auto-pr workflow
  .github/pull_request_template.md
  .github/workflows/auto-pr.yml
  dist/tsconfig.tsbuildinfo
  package.json
Labels: chore

#45 fix(ci): Sincronizar pnpm-lock.yaml y estabilizar el workflow
  .gitignore
  pnpm-lock.yaml
Labels: needs-review, bugfix, chore

#46 feat(course): Implementar creación de cursos con contenido anidado
  dist/tsconfig.tsbuildinfo
  src/models/course/course.controller.ts
  src/models/course/course.entity.ts
  src/models/course/course.schemas.ts
  src/models/course/course.services.ts
  src/models/course/embeddables/activity.entity.ts
  src/models/course/embeddables/material.entity.ts
  src/models/course/embeddables/unit.entity.ts
  src/models/course/schemas/course.schemas.ts
Labels: needs-review, feature

#47 refactor(courseType): Estandarizar arquitectura del módulo 'courseType'
  dist/tsconfig.tsbuildinfo
  src/models/courseType/courseType.controller.ts
  src/models/courseType/courseType.routes.ts
  src/models/courseType/courseType.schemas.ts
  src/models/courseType/courseType.services.ts
Labels: needs-review, refactor

#51 Refactor/standardize institution module
  dist/tsconfig.tsbuildinfo
  src/auth/auth.service.ts
  src/models/institution/institution.controller.ts
  src/models/institution/institution.entity.ts
  src/models/institution/institution.routes.ts
  src/models/institution/institution.schemas.ts
  src/models/institution/institution.services.ts
Labels: needs-review, refactor

#53 refactor(professor): Estandarizar arquitectura del módulo 'professor'
  src/models/professor/professor.controller.ts
  src/models/professor/professor.entity.ts
  src/models/professor/professor.routes.ts
  src/models/professor/professor.schema.ts
  src/models/professor/professor.services.ts
Labels: needs-review, refactor

#56 Refactor: middleware para control de errores global
  dist/tsconfig.tsbuildinfo
  src/app.ts
  src/models/appeal/appeal.controller.ts
  src/models/course/course.controller.ts
  src/models/courseType/courseType.controller.ts
  src/models/institution/institution.controller.ts
  src/models/professor/professor.controller.ts
  src/models/student/student.controller.ts
  src/shared/middlewares/error.middleware.ts
Labels: needs-review, refactor

#78 feat: Implementación de autorización basada en roles (RBAC)
  dist/tsconfig.tsbuildinfo
  src/auth/auth.middleware.ts
  src/models/appeal/appeal.routes.ts
  src/models/course/course.routes.ts
  src/models/courseType/courseType.routes.ts
  src/models/institution/institution.routes.ts
  src/models/professor/professor.routes.ts
  src/models/student/student.routes.ts
Labels: needs-review, feature
