Repository upskill-team/Back-End-DSW, pull requests merged in 2025-09, with the labels that each got.

#77 Feature/add swagger openapi
  dist/tsconfig.tsbuildinfo
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/models/institution/institution.routes.ts
  src/shared/swagger/swagger.ts
Labels: needs-review, feature

#82 feat: Configuración de rate limiting y cabeceras de seguridad con Helmet
  dist/tsconfig.tsbuildinfo
  package.json
  pnpm-lock.yaml
  src/app.ts
Labels: needs-review, feature

#83 Feature: Setup Database Migrations
  README.md
  mikro-orm.config.ts
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/migrations/Migration20250901183449.ts
  src/shared/db/orm.ts
Labels: feature

#93 fix: Fixed the routing problem in app.ts
  package.json
  pnpm-lock.yaml
  src/app.ts
Labels: bugfix

#115 Chore: Externalizar la documentación de Swagger en un yaml
  eslint.config.js
  src/app.ts
  src/docs/README.md
  src/docs/institutions.docs.yaml
  src/docs/swagger.config.ts
  src/models/institution/institution.routes.ts
  src/shared/swagger/swagger.ts
Labels: documentation, needs-review, refactor, chore

#116 Refactor: Eliminar entidad obsoleta Activity
  src/migrations/Migration20250904191600_RemoveActivityEntity.ts
  src/models/course/course.schemas.ts
  src/models/course/course.services.ts
  src/models/course/embeddables/activity.entity.ts
  src/models/course/embeddables/unit.entity.ts
Labels: needs-review, refactor
